apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: studysound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
        - name: frontend-app
          image: frontend-image:latest # Replace with your image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
