apiVersion: v1
kind: Service
metadata:
  name: frontend-app-service
  namespace: studysound
spec:
  selector:
    app: frontend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
