apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-svc-config
  namespace: notification-svc
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "*"
  # PostgreSQL (non-sensitive)
  DB_NAME: "notification_db"
  DB_USER: "postgres"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_CONN_MAX_AGE: "60"
  # Kafka
  KAFKA_ENABLED: "True"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  KAFKA_CONSUMER_GROUP: "notification-svc"
  KAFKA_TOPICS: "waste-events,bin-events,payment-events"
  DEFAULT_FROM_EMAIL: "noreply@waste-management.io"
