apiVersion: v1
data:
  db-password: cG9zdGdyZXM=
  email-host-password: ""
  email-host-user: ""
  secret-key: Y2hhbmdlLW1lLWluLXByb2R1Y3Rpb24=
  twilio-account-sid: ""
  twilio-auth-token: ""
kind: Secret
metadata:
  name: notification-svc-secrets
  namespace: notification-svc
