apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  namespace: notification-svc
  labels:
    app: notification-svc
spec:
  selector:
    app: notification-svc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
